SkinChecker/urls.py
from django.contrib import admin
from django.urls import path, include
from SkinChecker import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL,document_root =settings.STATIC_ROOT)

main_app/urls.py
from django.urls import path
from main_app.views import *

app_name = 'main_app'


urlpatterns = [
    path('', MainView.as_view(), name='index'),
    path('search/all', AllDiseasesView.as_view(), name='search_all'),
    path('search', SearchView.as_view(), name='search'),
]

main_app/models.py
from django.db import models
from taggit.managers import TaggableManager
from PIL import Image

def crop_center(pil_img, crop_width: int, crop_height: int) -> Image:
    """
    Функция для обрезки изображения по центру.
    """
    img_width, img_height = pil_img.size
    return pil_img.crop(((img_width - crop_width) // 2,
                         (img_height - crop_height) // 2,
                         (img_width + crop_width) // 2,
                         (img_height + crop_height) // 2))


class Disease(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(unique=True, max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    symptoms = TaggableManager()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open('media/' + str(self.image))
            x = crop_center(img, min(img.size), min(img.size))
            x.save('media/' + str(self.image))

main_app/forms.py
from django import forms

class SymptomsForm(forms.Form):

main_app/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views import View
from taggit.models import Tag
from django.http import HttpRequest
from main_app.models import Disease

def get_list_of_symptoms():
    symptoms = list(Tag.objects.all())
    q = []
    for i in symptoms:
        q.append(i.slug)
    print(', '.join(q))
    s = []
    for i in range(1, len(symptoms), 2):
        s.append([symptoms[i - 1], symptoms[i]])
    return s


class MainView(View):
    def get(self, request, *args, **kwargs):
        s = get_list_of_symptoms()
        return render(
            request,
            template_name='index.html',
            context={
                'symptoms': s
            }
        )


class SearchView(View):
    def get(self, request, *args, **kwargs):
        symptoms = []
        try:
            for i in request.GET:
                symptoms.append(Tag.objects.get(slug=i))
        except:
            return redirect('main_app:index')
        if len(symptoms) == 0:
            return redirect('main_app:index')
        diseases = Disease.objects.all()
        result = {}
        for disease in diseases:
            cnt = 0
            for symp in symptoms:
                if symp in disease.symptoms.all():
                    cnt += 1
            if cnt > 0 and cnt >= (len(symptoms) + 1) // 2:
                result[disease] = (-cnt, len(disease.symptoms.all()))

        print(sorted(result.keys(), key=lambda x: result[x]))
        return render(request,
                      template_name='search.html',
                      context={
                          'symptoms': get_list_of_symptoms(),
                          'result': sorted(result.keys(), key=lambda x: result[x])[:9],
                          'symptoms_str': 'Заболевания с симптомами: ' + ', '.join(request.GET).capitalize()
                      })

class AllDiseasesView(View):
    def get(self, request, *args, **kwargs):
        diseases = list(Disease.objects.all())
        print(diseases)
        return render(request,
                      template_name='search.html',
                      context={
                          'symptoms': get_list_of_symptoms(),
                          'result': diseases,
                          'symptoms_str': 'Все заболевания'
                      })

templates/about.html
<!-- About Section-->
        <section class="page-section bg-primary text-white mb-0" id="about">
            <div class="container">
                <!-- About Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-white">О НАС</h2>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-plus"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- About Section Content-->
                <div class="row">
                    <div class="col-lg-4 ms-auto"><p class="lead">Все мы знаем, как сложно искать нужную информацию в интернете. Особенно сложно постановить диагноз какой-либо болезни. Тем более есть риск постановить неверный диагноз.</p></div>
                    <div class="col-lg-4 me-auto"><p class="lead">В "Skin Health Checker" мы попробовали решить эту проблему. Вам нужно лишь выбрать симптомы и нажать "Найти!". Наш сайт поможет вам легко и просто найти какое-либо кожное заболевание. </p></div>
                </div>
                <div class="row mt-5">
                    <div class ="col ms-auto"><strong>Внимание!</strong><p class="lead"> Не рекомендуем использовать информацию из данного раздела для самолечения. На сайте представлена информация для ознакомления с кожными заболеваниями. В случае боли или иного обострения заболевания диагностические исследования должен назначать только лечащий врач. Для правильного назначения лечения следует обращаться к врачу.</p></div>
                </div>
            </div>
        </section>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static '/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static '/css/styles.css' %}">
    </head>
    <body id="page-top">
        {% include 'navbar.html' %}
        {% block body %}
        {% endblock %}
        {% include 'about.html' %}
        {% include 'footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/footer.html
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">ПОЧТА</h4>
                        <p class="lead mb-0">
                            kosenkov.n.p@mail.ru
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">соцсети</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="https://t.me/nikitakosp" target="_blank"><i class="fab fa-fw fa-telegram"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="https://github.com/nikitakosenkov" target="_blank"><i class="fab fa-fw fa-github"></i></a>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">КОМАНДА</h4>
                        <p class="lead mb-0">
                            CEO, Разработчик - <a href="https://github.com/nikitakosenkov" target="_blank">Косенков Никита</a>.
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; skin-health-checker.ru 2025</small></div>
        </div>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Skin Health Checker {% endblock %}

{% block body %}
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">Найдите кожное заболевание по симптомам легко и быстро!</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-plus"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0">Появились проблемы с кожей, и вы не знаете, что это может быть? Попробуйте выбрать симптомы, и мы предложим вам возможные заболевания.</p>
            </div>
        </header>
        <!-- Portfolio Section-->
        <section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Какие у вас симптомы?</h2>
                <p class="lead text-center font-weight-light mb-0 mt-3">Выберите до 5 симптомов.</p>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-plus"></i></div>
                    <div class="divider-custom-line"></div>
                </div>

                <div class="row mt-5">
                    <div class="container align-items-center justify-content-center">
                        <form name="symptoms-form" method="get" action="{% url 'main_app:search' %}">
                        {% for s in symptoms %}
                            <div class="row mx-auto" style="width: 70%">
                                {% for symptom in s %}
                                  <div class="col-md">
                                      <input name="{{ symptom.slug }}" class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                                      <label class="form-check-label" for="flexCheckDefault">
                                          <h5 class="font-weight-light">
                                              {{ symptom }}
                                          </h5>
                                      </label>
                                  </div>
                                {% endfor %}
                            </div>

                        {% endfor %}
                        <div class="text-center">
                            <button class="btn btn-primary btn-xl mt-5" id="submitSymptomButton" type="submit">Найти!</button>
                            <a class="btn btn-xl btn-outline-primary mt-5" href="{% url 'main_app:search_all' %}">Все заболевания</a>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                {% if not symptoms_str %}
                  <a class="navbar-brand" href="#page-top">Skin Health Checker</a>
                {% else %}
                  <a class="navbar-brand" href="{% url 'main_app:index' %}">Skin Health Checker</a>
                {% endif %}
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#portfolio">Поиск</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#about">О нас</a></li>
                    </ul>
                </div>
            </div>
        </nav>

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Skin Health Checker {% endblock %}

{% block body %}
  <!-- Portfolio Section-->
        <section class="page-section portfolio" id="portfolio">

            <div class="container">
                <nav aria-label="breadcrumb" class="my-4 p-2 rounded" style="background-color: #f1f1f1">
                    <ol class="breadcrumb mb-0 ps-2">
                      <li class="breadcrumb-item"><a href="{% url 'main_app:index' %}">Главная</a></li>
                      <li class="breadcrumb-item active" aria-current="page">{{ symptoms_str }}</li>
                    </ol>
                </nav>
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-1 mt-5">{{ symptoms_str }}</h2>
                <!-- Icon Divider-->

                {% if result %}
                    <p class="lead text-center font-weight-light mb-0 mt-3">Найдено заболеваний: {{ result|length }}</p>
                    <div class="divider-custom">
                        <div class="divider-custom-line"></div>
                        <div class="divider-custom-icon"><i class="fas fa-plus"></i></div>
                        <div class="divider-custom-line"></div>
                    </div>
                    <section class="all-posts">
                        <div class="container">
                            <div class="row justify-content-center">
                                {% for disease in result %}
                                    <div class="col-md-6 col-lg-4 mb-5 col-sm-6">
                                        <div class="card mb-4 shadow-sm">
                                            <img src="../media/{{disease.image}}" alt="" class="card-img-top">
                                            <div class="card-body">
                                                <h4 class="card-title">{{ disease.title|truncatechars:20 }}</h4>
                                                <p class="card-text" style="font-size: 17px">{{disease.description|safe|truncatechars:80 }}</p>
                                                <div class="mb-3">
                                                    {% for tag in disease.symptoms.all %}
                                                        <span class="badge text-bg-primary " style="font-size: 14px">{{tag}}</span>
                                                    {% endfor %}
                                                </div>
                                                <div class="d-flex justify-content-between align-items-center">
                                                    <div class="btn-group">
                                                        <a data-bs-toggle="modal" data-bs-target="#portfolioModal_{{disease.slug}}" class="btn btn-sm btn-outline-secondary">Подробнее</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </section>
                {% else %}
                    <div class="divider-custom">
                        <div class="divider-custom-line"></div>
                        <div class="divider-custom-icon"><i class="fas fa-plus"></i></div>
                        <div class="divider-custom-line"></div>
                    </div>
                  <h5 class="text-center">Заболеваний с такими симптомами не найдено. Пожалуйста, попробуйте выбрать другие симптомы.</h5>
                {% endif %}

                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-plus"></i></div>
                    <div class="divider-custom-line"></div>
                </div>

                <h2 class="text-center mt-5">Не нашли то, что искали? Попробуйте выбрать другие симптомы.</h2>

                <div class="row mt-5">
                    <div class="container align-items-center justify-content-center">
                        <form name="symptoms-form" method="get" action="{% url 'main_app:search' %}">
                        {% for s in symptoms %}
                            <div class="row mx-auto" style="width: 70%">
                                {% for symptom in s %}
                                  <div class="col-md">
                                      <input name="{{ symptom.slug }}" class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                                      <label class="form-check-label" for="flexCheckDefault">
                                          <h5 class="font-weight-light">
                                              {{ symptom }}
                                          </h5>
                                      </label>
                                  </div>
                                {% endfor %}
                            </div>

                        {% endfor %}
                        <div class="text-center">
                            <button class="btn btn-primary btn-xl mt-5" id="submitSymptomButton" type="submit">Найти!</button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        {% for disease in result %}
        <div class="portfolio-modal modal fade" id="portfolioModal_{{disease.slug}}" tabindex="-1" aria-labelledby="portfolioModal_{{disease.slug}}" aria-hidden="true">
            <div class="modal-dialog modal-xl">
                <div class="modal-content">
                    <div class="modal-header border-0"><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div>
                    <div class="modal-body text-center pb-5">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-lg-8">
                                    <!-- Portfolio Modal - Title-->
                                    <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">{{disease.title}}</h2>
                                    <!-- Icon Divider-->
                                    <div class="divider-custom">
                                        <div class="divider-custom-line"></div>
                                        <div class="divider-custom-icon"><i class="fas fa-plus"></i></div>
                                        <div class="divider-custom-line"></div>
                                    </div>
                                    <!-- Portfolio Modal - Image-->
                                    <img class="img-fluid rounded mb-5" src="../media/{{disease.image}}" alt="..." />
                                    <!-- Portfolio Modal - Text-->
                                    <p class="mb-4" style="font-size: 20px">{{disease.description}}</p>
                                    <div class="mb-5">
                                        <strong style="font-size: 18px">Симптомы:</strong>
                                        {% for tag in disease.symptoms.all %}
                                            <span class="badge text-bg-primary mb-1" style="font-size: 17px">{{tag}}</span>
                                        {% endfor %}
                                    </div>
                                    <button class="btn btn-primary" data-bs-dismiss="modal">
                                        <i class="fas fa-xmark fa-fw"></i>
                                        Close Window
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
{% endblock %}